CREATE TABLE IF NOT EXISTS cycle (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    firstname TEXT NOT NULL,
    adminacct BOOLEAN,
    startdate DATE,
    enddate DATE
);